### ISSUE TITLE
Prompt before execution 

### ISSUE THREAD

**Issue by Narretz** [fardjad/node-interactive-commander#254]
Hi, this looks very cool!

However, instead of prompts for the input, I'm looking for a prompt that is shown *after* options parsing but *before* actual execution of the script. Obviously I could do this with an option that must be set to true, but I want to do it interactively. Is this even the right library for this?

**Comment by fardjad** [comment]
Thank you!

I might be able to help you better if you share a small code snippet on what you're trying to do.

Also, you might find my other library, [parse-my-command](https://github.com/fardjad/node-parse-my-command) useful for parsing the args. Then you can implement the logic for showing the prompt yourself.

**Comment by Narretz** [comment]
Hi @fardjad thanks for the quick response. I figured out that what I want to do doesn't require your lib. Basically I just want to prompt before doing something like this:

```
import { confirm } from '@inquirer/prompts';
import { program } from 'commander';

program.command('command<data>').action(async (data, options, command) => {
  await confirm({ message: 'Run the command?' });

  console.log('success', data);
});
```

I didn't think it was that easy ;)
